version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: session-experiment-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: session_experiment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
